import { VoiceEntry } from './types';

// Mock data from the CSV file
export const mockVoiceEntries: VoiceEntry[] = [
  {
    id: "1",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I kind of don't want to go to the party, but I also don't want them to think I'm avoiding them.",
    transcript_user: "I kind of don't want to go to the party, though I also don't want them to think I'm avoiding them.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-10T08:00:00Z",
    updated_at: "2025-05-10T08:05:00Z",
    emotion_score_score: 0.05,
    embedding: null
  },
  {
    id: "2",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I turned down that opportunity. I think it was the right call, but there's still a small part of me that wonders.",
    transcript_user: "I turned down that opportunity. I think it was the right call, though there's still a small part of me that wonders.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-11T08:00:00Z",
    updated_at: "2025-05-11T08:05:00Z",
    emotion_score_score: 0.1,
    embedding: null
  },
  {
    id: "3",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I know I should sleep earlier, but I always end up scrolling late into the night.",
    transcript_user: "I know I should sleep earlier, though I always end up scrolling late into the night.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-12T08:00:00Z",
    updated_at: "2025-05-12T08:05:00Z",
    emotion_score_score: 0.14,
    embedding: null
  },
  {
    id: "4",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "He made some good points, but I can't help feeling like I'm still right.",
    transcript_user: "He made some good points, though I can't help feeling like I'm still right.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-13T08:00:00Z",
    updated_at: "2025-05-13T08:05:00Z",
    emotion_score_score: 0.18,
    embedding: null
  },
  {
    id: "5",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I said I'd help her out, and now I'm swamped. I don't want to back out, but I'm overwhelmed.",
    transcript_user: "I said I'd help her out, and now I'm swamped. I don't want to back out, though I'm overwhelmed.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-14T08:00:00Z",
    updated_at: "2025-05-14T08:05:00Z",
    emotion_score_score: 0.23,
    embedding: null
  },
  {
    id: "6",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I planned to work out today, but I was exhausted from work. Now I feel guilty for skipping it.",
    transcript_user: "I planned to work out today, but I was exhausted from work. Now I feel guilty for skipping it.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-15T08:00:00Z",
    updated_at: "2025-05-15T08:05:00Z",
    emotion_score_score: 0.27,
    embedding: null
  },
  {
    id: "7",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I told myself this was a smart long-term move, but honestly I think I just didn't want to deal with the current situation.",
    transcript_user: "I told myself this was a smart long-term move, but honestly I think I just didn't want to deal with the current situation.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-16T08:00:00Z",
    updated_at: "2025-05-16T08:05:00Z",
    emotion_score_score: 0.32,
    embedding: null
  },
  {
    id: "8",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "This relationship makes me happy, but there's always this quiet anxiety underneath.",
    transcript_user: "This relationship makes me happy, but there's always this quiet anxiety underneath.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-17T08:00:00Z",
    updated_at: "2025-05-17T08:05:00Z",
    emotion_score_score: 0.36,
    embedding: null
  },
  {
    id: "9",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I know he's not right for me, but I still want to give it one more try.",
    transcript_user: "I know he's not right for me, but I still want to give it one more try.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-18T08:00:00Z",
    updated_at: "2025-05-18T08:05:00Z",
    emotion_score_score: 0.41,
    embedding: null
  },
  {
    id: "10",
    user_id: "user1",
    audio_url: null,
    transcript_raw: "I said it doesn't bother me, but it actually does, more than I expected.",
    transcript_user: "I said it doesn't bother me, but it actually does, more than I expected.",
    language_detected: "en",
    language_rendered: "en",
    tags_model: [],
    tags_user: [],
    category: null,
    created_at: "2025-05-19T08:00:00Z",
    updated_at: "2025-05-19T08:05:00Z",
    emotion_score_score: 0.45,
    embedding: null
  }
];
